
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class Constants : Luban.BeanBase
{
    public Constants(ByteBuf _buf) 
    {
        GameName = _buf.ReadString();
    }

    public static Constants DeserializeConstants(ByteBuf _buf)
    {
        return new Constants(_buf);
    }

    public readonly string GameName;
   
    public const int __ID__ = 1581691183;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "GameName:" + GameName + ","
        + "}";
    }
}

}

