
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg.Items
{
public sealed partial class ItemTemplate : Luban.BeanBase
{
    public ItemTemplate(JsonElement _buf) 
    {
        Id = _buf.GetProperty("id").GetString();
        Desc = _buf.GetProperty("desc").GetString();
        ItemType = (Items.ItemType)_buf.GetProperty("item_type").GetInt32();
        MaxStack = _buf.GetProperty("max_stack").GetInt32();
    }

    public static ItemTemplate DeserializeItemTemplate(JsonElement _buf)
    {
        return new Items.ItemTemplate(_buf);
    }

    public readonly string Id;
    public readonly string Desc;
    public readonly Items.ItemType ItemType;
    public readonly int MaxStack;
   
    public const int __ID__ = 238212187;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "desc:" + Desc + ","
        + "itemType:" + ItemType + ","
        + "maxStack:" + MaxStack + ","
        + "}";
    }
}

}

